enum {
    TD_PLUS_F1,
    TD_LBRC_F2,
    TD_LCBR_F3,
    TD_LPRN_F4,
    TD_AMPR_F5,
    TD_EQL_F6,
    TD_RPRN_F7,
    TD_RCBR_F8,
    TD_RBRC_F9,
    TD_ASTR_F10,
};

tap_dance_action_t tap_dance_actions[] = {
    [TD_PLUS_F1] = ACTION_TAP_DANCE_DOUBLE(KC_PLUS, KC_F1), [TD_LBRC_F2] = ACTION_TAP_DANCE_DOUBLE(KC_LBRC, KC_F2), [TD_LCBR_F3] = ACTION_TAP_DANCE_DOUBLE(KC_LCBR, KC_F3), [TD_LPRN_F4] = ACTION_TAP_DANCE_DOUBLE(KC_LPRN, KC_F4), [TD_AMPR_F5] = ACTION_TAP_DANCE_DOUBLE(KC_AMPR, KC_F5), [TD_EQL_F6] = ACTION_TAP_DANCE_DOUBLE(KC_EQL, KC_F6), [TD_RPRN_F7] = ACTION_TAP_DANCE_DOUBLE(KC_RPRN, KC_F7), [TD_RCBR_F8] = ACTION_TAP_DANCE_DOUBLE(KC_RCBR, KC_F8), [TD_RBRC_F9] = ACTION_TAP_DANCE_DOUBLE(KC_RBRC, KC_F9), [TD_ASTR_F10] = ACTION_TAP_DANCE_DOUBLE(KC_ASTR, KC_F10),
};
