# VIA_ENABLE = yes
# VIAL_ENABLE = yes

# TAP_DANCE_ENABLE = no
# COMBO_ENABLE = no
# KEY_OVERRIDE_ENABLE = no

TAP_DANCE_ENABLE = yes
# COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

LTO_ENABLE = yes
CAPS_WORD_ENABLE = yes
